### PR TITLE
Add astro support

### PR DESCRIPTION
**Pull request by EliasLeguizamon123**
This PR add astro support: https://astro.build
 Mentioned in #34 
 
 - [x] If this language conflicts with another language (same extension), I've added heuristics
 - [x] If this language conflicts with another language, I've linked to the pull request that added the other language here:

### CODE REVIEW

**Comment by spenserblack** [comment]
Fantastic! Would you also be able to add a sample to the `samples-test/samples/` folder?

**Comment by spenserblack** [comment]
@all-contributors add @EliasLeguizamon123 for data

**Comment by EliasLeguizamon123** [comment]
> Fantastic! Would you also be able to add a sample to the `samples-test/samples/` folder?

Hi @spenserblack, I've been looking through the samples folder and the documentation, but I'm unsure about what kind of sample I could add.

**Comment by spenserblack** [comment]
The sample can be anything, it just has to be a good representation of the language. For example, if I was making a Python sample:

## Not a good sample

```python
print("Hello, World!")
```

## A better sample

```python
from uuid import uuid4
from unittest import TestCase

class Item:
    def __init__(self):
        self.id = uuid4()

class Charcoal(Item):
    pass

class Stick(Item):
    def __add__(self, other):
        return Torch(self, other)

class Torch(Item):
    def __init__(self, stick: Stick, charcoal: Charcoal):
        super().__init__()
        self.stick = stick
        self.charcoal = charcoal

    def components(self):
        return [self.stick, self.charcoal]

class TestMinecraft(TestCase):
    def test_torch(self):
        stick = Stick()
        charcoal = Charcoal()
        torch = stick + charcoal
        components = torch.components()

        self.assertIn(charcoal, components)
        self.assertIn(stick, components)
```

---

The second example is better because it showcases language features, like imports, classes, and methods. Right now the samples serve one purpose: to run tests to prove that `gengo` identifies the correct language for "real world" files.

But in the future the samples may be used to train a classifier, which is why the samples should be more than a "hello world" and contain significant syntax.

Hope this helps! Also, feel free to make a PR to update the docs if they weren't clear enough :slightly_smiling_face:

**Comment by EliasLeguizamon123** [comment]
> The sample can be anything, it just has to be a good representation of the language. For example, if I was making a Python sample:
> 
> ## Not a good sample
> ```python
> print("Hello, World!")
> ```
> 
> ## A better sample
> ```python
> from uuid import uuid4
> from unittest import TestCase
> 
> class Item:
>     def __init__(self):
>         self.id = uuid4()
> 
> class Charcoal(Item):
>     pass
> 
> class Stick(Item):
>     def __add__(self, other):
>         return Torch(self, other)
> 
> class Torch(Item):
>     def __init__(self, stick: Stick, charcoal: Charcoal):
>         super().__init__()
>         self.stick = stick
>         self.charcoal = charcoal
> 
>     def components(self):
>         return [self.stick, self.charcoal]
> 
> class TestMinecraft(TestCase):
>     def test_torch(self):
>         stick = Stick()
>         charcoal = Charcoal()
>         torch = stick + charcoal
>         components = torch.components()
> 
>         self.assertIn(charcoal, components)
>         self.assertIn(stick, components)
> ```
> 
> The second example is better because it showcases language features, like imports, classes, and methods. Right now the samples serve one purpose: to run tests to prove that `gengo` identifies the correct language for "real world" files.
> 
> But in the future the samples may be used to train a classifier, which is why the samples should be more than a "hello world" and contain significant syntax.
> 
> Hope this helps! Also, feel free to make a PR to update the docs if they weren't clear enough 🙂

Sure mate, count on me. Give me a couple of days to finish some personal projects, and I'll add an example for Astro in a new PR 😄 @spenserblack

**Comment by spenserblack** [comment]
Thanks!

**Pull request merged**
