### PR TITLE
add c# support

### PR DESCRIPTION
**Pull request by o2sh**

### CODE REVIEW

**Review by spenserblack — APPROVED** [review]
Thanks for the spelling fix :laughing:

Once you mispell something once, Copilot likes to mispell everywhere.

On mobile right now so I can't really check, but the `#` doesn't require any quoting?

Also, you want to be a collaborator?

**Comment by spenserblack** [comment]
Oh, also, do you anticipate the `cs` extension conflicting with anything? The heuristic is welcome, but not required if there are no reasonable conflicts.

**Review by spenserblack — APPROVED** [review]

**Comment by spenserblack** [comment]
Sorry, just thought of one last thing: were you able to check if the language override works with this special character? I was unsure about the gitattributes parsing, and if I needed to implement aliases.

**Comment by o2sh** [comment]
>Oh, also, do you anticipate the cs extension conflicting with anything? The heuristic is welcome, but not required if there are no reasonable conflicts.

Yes according to [linguist](https://github.com/github-linguist/linguist/blob/916bd8f3df802fa98b0ea85539e67bd0b88ef158/lib/linguist/languages.yml#L716), c# is associated with `.cs`, `.csx`, `.linq` and `.cake`, [tokei](https://github.com/XAMPPRocky/tokei/blob/ae77e1945631fd9457f7d455f2f0f2f889356f58/languages.json#L273C20-L273C20) only mentions `.cs` and `.csx`. I couldn't find any information on `.linq` however, so I may leave it out 🤔

**Comment by spenserblack** [comment]
Oh, browsing through linguist, I see that Smalltalk uses the `.cs` extension, too. So, yeah, the heuristic definitely helps future-proof :slightly_smiling_face:

**Comment by spenserblack** [comment]
BTW, about `.linq`: https://github.com/github-linguist/linguist/commit/8866bb05a7f595d7b13ed4d9953dd2060c02c26e

**Comment by spenserblack** [comment]
@all-contributors add @o2sh for data

**Pull request merged**
